### PR TITLE
Release v10.4.7

### PR DESCRIPTION
**Pull request by smalluban**
0f56a9214dcaff828cdc37faf0c18289253acb72 Update @whotracksme/reporting dependency (#1895)
4a69215fc68b74f701de35a461d7cbb1e7535c88 fix: add CJK characters support to `ui-text` component (#1893)
449d0fa99c7a4c08a5bb2683f890b7e17f9d4006 fix: update the dark mode & ui components clean up (#1888)
5a80a73f622c800c0945a567cba90ab498ce14b4 fix: add TrackerDB `Utilities` category (#1892)
63d44c0705699438521a9d19f52db9d1dfd8eea7 Release tests documentation (#1873)
8dd540eb3c649f795512595690a624d0430d8185 fix: youtube & iframe util from packages/ui to main source (#1884)
03367332110bc291725b9ad0c004738e9965fee1 Include also the subdomain information when doing a TrackerDB lookup. (#1889)

### CODE REVIEW

**Comment by AdamGhst** [comment]
10.4.7 Report

FF and CHROME are good. 

SAFARI: 
- YT - video ads (pre roll) are not visible, but the loading time of a actual video is same as lenght on ad. So ad is not visible, but it is played. There are no other ads visible on the service.

**Comment by smalluban** [comment]
7da14846035cd3c3e71319f8f25e91c18ea9715e fix: onboarding background gradient in light mode

**Review by AdamGhst — CHANGES_REQUESTED** [review]
10.4.7 Report

FF and CHROME are good.

SAFARI:

    YT - video ads (pre roll) are not visible, but the loading time of a actual video is same as lenght on ad. So ad is not visible, but it is played. There are no other ads visible on the service.

**Comment by smalluban** [comment]
@AdamGhst The YT problem is random (in the video you posted elsewhere only after 5 reloads of the page the ad is displayed). I doubt that this is related to the code in the release (cosmetic filters are updated regardless of the source code).

If you haven't found other issue, please re-review ;)

**Review by AdamGhst — APPROVED** [review]

**Pull request merged**
