### PR TITLE
GH-1592 (8.4.0 release): Update Tutorial Images in Hub

### PR DESCRIPTION
**Pull request by Eden12345**
JIRA Ticket: https://cliqztix.atlassian.net/browse/GH-1592

**Note**
These images won't match the Ghostery extension until the UI refresh is complete for the 8.3.4 release, so we should wait to merge it until then.

* [x] Have you followed the guidelines in [CONTRIBUTING.md](../CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you added an explanation of what your changes do?
* [x] Does your submission pass tests?
* [x] Did you lint your code prior to submission?

### CODE REVIEW

**Comment by Eden12345** [comment]
Vinny is looking into the images that I pulled from Zeplin to see why they don't all match up.

I'm pretty sure /tutorial/5 looked the same in the last version so I didn't change the CSS, but I'm happy to update the styling in this branch so they're lined up.

I think /tutorial/3 has a different break-point than the other views because the legend looked strange when placed above the images at a greater width than the current break-point. Happy to change that now as well, though.

**Comment by Eden12345** [comment]
Vinny updated the images in the Zeplin project that's linked in the JIRA ticket. I'll add them in and make the other styling changes when 8.3.4 rolls around.

**Comment by IAmThePan** [comment]
We will need new images when the new Panel UI is complete.  Hold off merging this PR until then.
When we do have new images please
- Scale them down in size, no need having extra large images.
- Run the scaled down images through an image compressor to ensure File Size increase is minimal.

**Comment by jsignanini** [comment]
Waiting on the latest screenshot images to be added to `GH-1592`.

**Comment by wlycdgr** [comment]
The new images have been scsled down, compressed, and swapped in and the layouts have been adjusted to improve consistency between pages and alignment within pages. Vinnie has signed off on how it looks. Ready for re-review.

**Comment by wlycdgr** [comment]
> @wlycdgr looks good! Last thing, I see permissions for many of the images were changed from `0644` to `0755`, could you change them back to `0644` please?

Done

**Pull request merged**
