### PR TITLE
Release 8.12.10

### PR DESCRIPTION
**Pull request by chrmod**

### CODE REVIEW

**Comment by chrmod** [comment]
[ghostery-chrome-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15220309/ghostery-chrome-v8.12.10.zip)
[ghostery-edge-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15220312/ghostery-edge-v8.12.10.zip)
[ghostery-firefox-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15220313/ghostery-firefox-v8.12.10.zip)

**Comment by chrmod** [comment]
[ghostery-chrome-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15221804/ghostery-chrome-v8.12.10.zip)
[ghostery-edge-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15221806/ghostery-edge-v8.12.10.zip)
[ghostery-firefox-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15221807/ghostery-firefox-v8.12.10.zip)

**Review by philipp-classen — APPROVED** [review]

**Comment by philipp-classen** [comment]
This upcoming release should also fix the problem in https://github.com/ghostery/trackerdb/issues/266

**Comment by chrmod** [comment]
[ghostery-chrome-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15222476/ghostery-chrome-v8.12.10.zip)
[ghostery-edge-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15222480/ghostery-edge-v8.12.10.zip)
[ghostery-firefox-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15222482/ghostery-firefox-v8.12.10.zip)

**Comment by GRadziejewski** [comment]
Tests result: https://github.com/ghostery/ghostery-extension/issues/1578#issuecomment-2095988395

**Comment by chrmod** [comment]
[ghostery-edge-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15234880/ghostery-edge-v8.12.10.zip)
[ghostery-firefox-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15234881/ghostery-firefox-v8.12.10.zip)
[ghostery-chrome-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15234879/ghostery-chrome-v8.12.10.zip)

**Comment by GRadziejewski** [comment]
Tests result: https://github.com/ghostery/ghostery-extension/issues/1578#issuecomment-2098225056 of this version: https://github.com/ghostery/ghostery-extension/pull/1576#issuecomment-2098208436

**Comment by chrmod** [comment]
[ghostery-chrome-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15237774/ghostery-chrome-v8.12.10.zip)
[ghostery-edge-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15237775/ghostery-edge-v8.12.10.zip)
[ghostery-firefox-v8.12.10.zip](https://github.com/ghostery/ghostery-extension/files/15237776/ghostery-firefox-v8.12.10.zip)

**Comment by GRadziejewski** [comment]
Tests result: https://github.com/ghostery/ghostery-extension/issues/1578#issuecomment-2098782743 of this version: https://github.com/ghostery/ghostery-extension/pull/1576#issuecomment-2098746657

**Pull request merged**
