### PR TITLE
Fix cookie whitelisting

### PR DESCRIPTION
**Pull request by sammacbeth**
Fixes the removal of the anti-tracking cookie whitelist step, which is required to prevent breakage for certain third-parties which require third-party cookies.

Also bumps browser-core and fixes resolution of the adblocker module.

### CODE REVIEW

**Comment by zarembsky** [comment]
New package still gives error on Edge and adblock is broken.
```Unhandled rejection: DataError: DataError
   at Ae.rejectionMapper (ms-browser-extension://MSG_name___C268A5FCA5B249D7A4AB9B429CCFCC74/dist/background.js:48:276626)
   at Ce (ms-browser-extension://MSG_name___C268A5FCA5B249D7A4AB9B429CCFCC74/dist/background.js:48:230068)
   at e (ms-browser-extension://MSG_name___C268A5FCA5B249D7A4AB9B429CCFCC74/dist/background.js:48:229518)
   at Ae (ms-browser-extension://MSG_name___C268A5FCA5B249D7A4AB9B429CCFCC74/dist/background.js:48:229172)
   at _promise (ms-browser-extension://MSG_name___C268A5FCA5B249D7A4AB9B429CCFCC74/dist/background.js:48:259431)
   at e (ms-browser-extension://MSG_name___C268A5FCA5B249D7A4AB9B429CCFCC74/dist/background.js:48:250909)
   at _trans (ms-browser-extension://MSG_name___C268A5FCA5B249D7A4AB9B429CCFCC74/dist/background.js:48:250671)
   at _idbstore (ms-browser-extension://MSG_name___C268A5FCA5B249D7A4AB9B429CCFCC74/dist/background.js:48:251229)```

**Comment by sammacbeth** [comment]
@zarembsky is it possible to give a trace that shows which database is causing the data error? If you have a test build I can try and find a windows machine to test locally.

**Comment by sammacbeth** [comment]
Updated the build to also fix issues on Edge.

**Comment by remusao** [comment]
@zarembsky is there any blocker to merge this one?

**Comment by remusao** [comment]
@jsignanini I can see the new yarn.lock being committed already. Am I missing something?

**Comment by jsignanini** [comment]
@remusao it appears to have `browser-core` listed twice. If you run `yarn` it should remove the irrelevant one.

**Comment by remusao** [comment]
Opened #345 with the updated yarn.lock.

**Comment by jsignanini** [comment]
closing since the above referenced PR has been merged.

**Pull request closed without merging**
