### PR TITLE
[l10n] Add breton translation

### PR DESCRIPTION
**Pull request by tornoz**
Add breton translation

### CODE REVIEW

**Comment by jsignanini** [comment]
Hi @tornoz!

Thank you for your contribution; however, Breton is currently not supported by the web stores Ghostery is available in. So unfortunately we will not be able to add this language until the stores support it.

For a list of supported language please follow this link: https://developer.chrome.com/webstore/i18n#localeTable

**Comment by ghostwords** [comment]
Which store would you have problems with, and what kind of problems? We haven't had any trouble supporting [Esperanto](https://github.com/EFForg/privacybadger/blob/master/src/_locales/eo/messages.json) (for example) with Privacy Badger.

**Comment by jsignanini** [comment]
Hey! I was going off of the chrome dev list [here](https://developer.chrome.com/webstore/i18n#localeTable). We are using chrome's i18n api which picks up the language from the operating system (on OS X). I tried switching to Esperanto and I wasn't able to get Privacy Badger to switch to it... can you confirm that Esperanto is working for you? I'm on OS X 0.13 (High Sierra).

**Comment by ghostwords** [comment]
I don't know how to do it in Chrome (there may not be a way as "eo" is not a known locale to Chrome), but I am able to use Esperanto in Firefox by following [Firefox's cumbersome multi-step directions](https://support.mozilla.org/en-US/kb/use-firefox-interface-other-languages-language-pack).

**Pull request closed without merging**
