### PR TITLE
Release 10.2.14

### PR DESCRIPTION
**Pull request by smalluban**
32c21601993a64f8e89ae7c0421fcc640a2d2d53 Downgrade webextension-pacakges for now (#1511)
6dcd3261cbdb10c85d493d9f6bc74be0af1e9eb4 Revert dev env to production ghostery.com
3f19b8ef9ff79b90840eead23c0502e9fd571145 Revert xcode entitlements
a5f8e93f1ecf392c4e9e15a70285874716ce622f Merge remote-tracking branch 'origin/main' into mv3-release
e9a152a5e7ec674e551b15e6817e86597cb256da Update webextension-packages (#1509)
572e7852750df0d968f6fa36b16c4afa762d842c Add contributor badge info to panel and settings page (#1505)
072ba856e637877ed21fdc92afa2e761b3f3ae6f feat: upgrade autoconsent to 10.3.2 (#1506)
a7e1e02df95a8e25b5e5bca4503ce1a1e1c73167 Grants the URL reporter access to the browser configuration (#1502)
d3843477d9fdacaf59e3a98b543293774ca0de56 Rollback app-sandox entitlement for macOS

TestFlight: v10.2.14 (151)

Target platforms: Opera, Ghostery Browser, Safari

### CODE REVIEW

**Comment by donaldpcook** [comment]
@smalluban @chrmod Will this be the next release, and if so, do you plan on pulling in updates since this was created? I'm trying to get an understanding of when https://github.com/ghostery/broken-page-reports/pull/586 will be available.

Thanks!

**Comment by smalluban** [comment]
@donaldpcook FIlters are auto-updating every 24 hours in both v8 (chrome, edge, firefox) and v10 (opera, safari, ghostery browser).

**Comment by smalluban** [comment]
@GRadziejewski Added required downgrade of the webextension-packages from @philipp-classen https://github.com/ghostery/ghostery-extension/pull/1511

Please do an additional fast sanity check of the Safari builds.

**Review by GRadziejewski — APPROVED** [review]

**Comment by GRadziejewski** [comment]
Tests results are here: https://github.com/ghostery/ghostery-extension/issues/1510#issuecomment-2015088712

**Pull request merged**
