### PR TITLE
Release v10.3.16

### PR DESCRIPTION
**Pull request by smalluban**
ffe7ec8a3fe4d19c5dc29f7fe97d833d9f5f84a8 Update webextension-package to 5.1.20
1bbb1f81a7d66f2522e381c4d8c38b4d51821e10 feat: update autoconsent to v10.12.1
a27910bcd59c894d644bf289702062352ee572d6 Detailed view tweaks (#1757)
aed282bec510ca1997f622e4fbd3a5f7d97c1e02 Fix UI for the protection status dialog (#1756)

Testing focus: panel tweaks and updated protection status dialog

### CODE REVIEW

**Comment by smalluban** [comment]
ecd2e1c7a3dacc2aa83b14a7b2adee1170b127b0 (origin/main, origin/HEAD, main) Revert "Clean up `ui-panel-list` usage, as slot header was removed (#1768)"

I was wrong about a fix - simple revert - only UI change (fix regression).

**Comment by smalluban** [comment]
Added #1776

**Comment by GRadziejewski** [comment]
The test results are here: https://github.com/ghostery/ghostery-extension/issues/1771#issuecomment-2265170410
There are three issues:

#1778
#1779
#1780

This should be fixed before the pushing to the production.

**Comment by smalluban** [comment]
#1778 has a fix on PR, the rest are closed (invalid). Waiting for #1782, then I'll push new build.

**Review by GRadziejewski — APPROVED** [review]

**Pull request merged**
