### PR TITLE
Onboarding spreadsheet bugs #38 (GH-2259), #44 (GH-2306), and #45 (GH-2305)

### PR DESCRIPTION
**Pull request by benstrumeyer**
* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/ghostery/ghostery-extension/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you added an explanation of what your changes do?
* [ ] Does your submission pass tests?
* [x] Did you lint your code prior to submission?

- Bug 38, Make Glow logo larger in search selection modal
- Bug 44, Center align ghostery glow icon with the box
- Bug 45, Select plus plan and expand selection if user is basic and has chosen ghostery search

### CODE REVIEW

**Review by wlycdgr — COMMENTED** [review]
Changes look good ~ Couple more things:

* I made a render helper for the checkmark items in the option cards and started refactoring the code to use it - if you could finish that up that would be great
* Let's factor the `isBasic`, `isPlus`, and `isPremium` checks out to helpers. First cos they're duplicated in `render` and `setDefaultPlan`, but also we reduce chance of error nicely with the logic for these checks being a bit convoluted.
* Speaking of `setDefaultPlan` - as far as I can tell from a combination of memory and double-checking just now, `setTimeout` is non-blocking, so with the code as it was, `render` would run before `setDefaultPlan` anyway (you can see this in action by setting `readyToRender` to `true` from the get-go and throwing in a couple consologs). To make sure we actually don't render until after `setDefaultPlan` has run after the timeout period, I added this `readyToRender` state variable that defaults to `false` and short-circuits `render` until it's set to `true at the end of `setDefaultPlan`. Nothing to do here at the moment really, just wanted to point this out (ultimately though it'd be good to update the `AccountReducer` so that we have a way of distinguishing between 'no user' and 'user data not fetched yet').
* I took the liberty of making some additional adjustments to search selection modal logo sizes to better match the Zeplins, since that was on me to begin with.

**Comment by wlycdgr** [comment]
> * I made a render helper for the checkmark items in the option cards and started refactoring the code to use it - if you could finish that up that would be great

Done

**Comment by wlycdgr** [comment]
> * Let's factor the `isBasic`, `isPlus`, and `isPremium` checks out to helpers. First cos they're duplicated in `render` and `setDefaultPlan`, but also we reduce chance of error nicely with the logic for these checks being a bit convoluted.

Done

**Comment by wlycdgr** [comment]
> * Speaking of `setDefaultPlan` - as far as I can tell from a combination of memory and double-checking just now, `setTimeout` is non-blocking, so with the code as it was, `render` would run before `setDefaultPlan` anyway (you can see this in action by setting `readyToRender` to `true` from the get-go and throwing in a couple consologs). To make sure we actually don't render until after `setDefaultPlan` has run after the timeout period, I added this `readyToRender` state variable that defaults to `false` and short-circuits `render` until it's set to `true` at the end of `setDefaultPlan`.  Nothing to do here at the moment really, just wanted to point this out (ultimately though it'd be good to update the `AccountReducer` so that we have a way of distinguishing between 'no user' and 'user data not fetched yet').

Reworked to call `componentDidMount` to avoid the hack of using `setTimeout` to `setState` "in" the `constructor`

**Comment by wlycdgr** [comment]
> * I took the liberty of making some additional adjustments to search selection modal logo sizes to better match the Zeplins, since that was on me to begin with. Let me know if you see that I screwed anything up and I'll fix.

Double checked that this looks ok, but a fresh pair of eyes would be appreciated

**Review by leuryr — APPROVED** [review]
LGTM

**Review by christophertino — APPROVED** [review]

**Pull request merged**
