### PR TITLE
Update vietnamese locale

### PR DESCRIPTION
**Pull request by tachibana-shin**
This pr updates vietnamese translations for mv3. I check the update by:
```ts
import { readFileSync } from "node:fs"

const en = JSON.parse(readFileSync("./en/messages.json", "utf8"))
const vi = JSON.parse(readFileSync("./vi/messages.json", "utf8"))

const diff = Object.fromEntries(
  Object.entries(en).filter(([key]) => !(key in vi))
)

console.log(diff)
```

### CODE REVIEW

**Comment by chrmod** [comment]
Hi @tachibana-shin - many thanks for the translations, those are much appreciated. Was thinking on a process to support you and other community members help us work on the translations. Can you please send me an email to chrmod <at> ghostery.com so we discuss this further?

**Review by chrmod — APPROVED** [review]

**Comment by tachibana-shin** [comment]
> Hi @tachibana-shin - many thanks for the translations, those are much appreciated. Was thinking on a process to support you and other community members help us work on the translations. Can you please send me an email to chrmod ghostery.com so we discuss this further?

I think a discussion on Discord is more open than using e-mail

**Comment by chrmod** [comment]
@tachibana-shin I appreciate the consideration for a transparent communication. The reason I've suggested email is so we can communicate not in public as I was going to propose you access to our translation platform - Transifex. And as we never done this with open-source contributors like you, we simply wanted to test the setup in a one-on-one conversation. Also to give you access the that platform we will need your email address, that is also why email seemed more appropriate. Hope this clarifies everything :)

**Comment by tachibana-shin** [comment]
> @tachibana-shin I appreciate the consideration for a transparent communication. The reason I've suggested email is so we can communicate not in public as I was going to propose you access to our translation platform - Transifex. And as we never done this with open-source contributors like you, we simply wanted to test the setup in a one-on-one conversation. Also to give you access the that platform we will need your email address, that is also why email seemed more appropriate. Hope this clarifies everything :)

Oh ok. I sended email. Please check inbox 😊

**Pull request merged**
