### PR TITLE
Release v10.4.5

### PR DESCRIPTION
**Pull request by smalluban**
5f025c097109a9e5785c79f3477947913ae7d8a5 fix: merge chromium-based browsers to one build (#1872)
6d810bd3c2807ffaddcaa5f63dc418b1c0ccb33c TrackerDB updates (#1871)
1f226fef0c13668237b500e56287ecf73d4d6c05 Strict extension CSP (#1870)
1f94d47ce413b4e40b3ec9bdfd5994394b4e49fb fix: fallback to storage.local when IndexedDB is corrupted (#1865)
0ec5da4520d0923c1cb3be5a53d569406eccd053 Telemetry: send active faster and remove upgrade signals (#1868)
f124dee676412bff2a5460237edffada225f87fd fix: regional filters list top margin
15734c35c90e7bf046ba193c393ff8498392f005 fix: panel pause button layout
e156c7e3c2ca46b42e14161f76ee877a666d612a Fix missing telemetry fields (#1863)
61ef4296fefef5513ae97753053276630d17a6db $replace modifier (#1842)
ca8eeed8ec0b876cacfb27b5470730b1e161cf5b chore: disable autoconsent cosmetics (#1864)
022f2b242c5288e9cef0ed5ad07d14f65f33f3fc fix: merge adblocker filter lists to one main engine (#1856)

### CODE REVIEW

**Comment by GRadziejewski** [comment]
**Issue 1:**

**Description**
No activity is visible when Ghostery is paused (it does not matter whether globally or on a specific page).

**Steps to Reproduce**
1. Open any website, for example: https://www.reuters.com/
2. Open Ghostery panel and click on "Pause on this site"
3. Wait for the reload of the website and open Ghostery panel again. There are no activities.
image
image

**Expected results**
There should be information on observed actions when Ghostery is paused.

Versions
```
Browser: Firefox 130.0
OS: Windows 10/11
GBE 10.4.5
```

**Comment by smalluban** [comment]
36b5d595748d44c0e88669991f98a4e02acf2c79 fix: add requests to stats when pause is turned on (#1876)

**Comment by GRadziejewski** [comment]
## Smoke tests Iteration no 1:
Tests of: https://github.com/ghostery/ghostery-extension/pull/1874#issuecomment-2340529368

---
Checked features:

- Onboarding 
  - Ghostery cannot work before onboarding
- Enable/Disable Ad-blocking 
- Enable/Disable Anti-tracking
- Enable/Disable Never Consent 
  -  Check website with </br> &emsp; - CPM Onetrust ([booking.com](https://www.ghostery.com/whotracksme/websites/booking.com)) 
  - Check website with </br> &emsp; - CPM Evidon ([playstation.com](https://www.ghostery.com/whotracksme/websites/playstation.com))
- Pause Ghostery
- Regional filters
- Custom filters
- Trackers Preview 
- Sign in/out
  - Check Sync from / into another device
- Google
  - Check YT
  - Check YT Kids

```
Browser: Chrome 128.0.6613.120
OS: Windows 10
GBE 10.4.5

Browser: Firefox 130.0
OS: Windows 10
GBE 10.4.5

Browser: Firefox 130.0
OS: Windows 11
GBE 10.4.5
```
---


## Issues:
- 

## Fixed:
- https://github.com/ghostery/ghostery-extension/issues/1861
- https://github.com/ghostery/ghostery-extension/issues/1862

## Cannot reproduce:
- 

## Will not be fixed:
-

**Review by GRadziejewski — APPROVED** [review]
LGTM

**Comment by smalluban** [comment]
@GRadziejewski Thanks for testing it out. I will make few tests how the extension works after update from 4.4, and merge the PR.

**Pull request merged**
