### PR TITLE
Release 10.1.4

### PR DESCRIPTION
**Pull request by chrmod**
d3889952412b47ad2861dbd14f388633f78bbd48 Fix trackers preview for endless scroll on SERP (#1275)
23f745042720db0abe1ab591d240f52bf5e2ba50 Tracker Preview: detect more Google layouts (#1282)
35d467d09ef934f6e22604cd2d8356d6b9783666 Dynamic content scripts for trackers preview and serp tracking (#1278)
f66c6ee2397a68eb9bdd3013cc20ae40e9e58835 Prevent from syncing not existing property (#1280)
3f7b401951582674aaf943328820f906884cf09b Follow the `true` default value for main options in the MV2 migration (#1281)
0926a2aeb76ce2873c52544470c145803b0de117 CI: upload named artefacts only on labeled PRs (#1277)
068efccb26652cbe83676cfbe7b6ee4de348ee96 Ghostery 10 packaging (#1272)
159b7d58efa064217457708b49246428a0f8ecc8 Move trackers-preview to the main repository (#1270)
ea2beeec83f4be619951256c798baaeb74eaf32b Fix options assignment for MV2 migration (#1271)
b832d188f7540617d4617ae6956bae8303964b41 Disable main features before terms are accepted (#1262)
0a9f35311aae1107e8ef845fa2d9f49991c0bc7b Catch for errors when trying to refresh user's session
dd8d02b47084f6320058a9c8363557be03748e38 Rename general `alarms.js` to `paused.js`
b257e6ccfc5dcb1f983135b0de1a4a95022873f0 Update Autoconsent
41833316e0577176d106c02fe2bdbdc6341d86aa Update WTM packages

## Testing highlights

* Fixes and change to dynamic loading on `trackers-preview`
* Switchable SERP tracking - new option in settings
* Minor fixes on session fetching (better catching errors) and options sync

### CODE REVIEW

**Comment by smalluban** [comment]
TestFlight: v10.1.4 (122)

**Comment by smalluban** [comment]
Discovered bug in trackers preview - https://github.com/ghostery/ghostery-extension/pull/1288

Wait with testing for merge and new build.

**Comment by GRadziejewski** [comment]
# Iteration nr 1.

## Smoke tests 

| Feature | Platform | Platform |
| :--- | :---: | :---: |
| X | 	OS: Android 11 GBE 10.1.4 |	OS: Android 13 GBE 10.1.4 |
| Install fresh (no profiles and etc) | ghosty_blue_2 | |
| Update |ghosty_blue_2  | |
| Ghostery cannot work before onboarding | ghosty_green_2  | |
| Onboarding | ghosty_green_2 | |
| Enable/Disable Ghostery | | |
| Enable/Disable Ad-blocking | | |
| Enable/Disable Anti-tracking | | |
| Pause Ghostery | | |
| Never Consent | | |
| Trackers Preview  | | |
| Select/Unselect any/all tracker/s | | |
| Sign in/out | | |
| Sign in and then update | | |
| Check Sync from / into another device | | |
| Check Ghostery Settings logs | | |
| Check Ghostery Background logs | | |
| Check account settings | | |
| Log into Google account and open google.com | | |
| Try to search anything | | |
| Try to search something with video | | |
| Log into FB | | |
| Update of the GBE | | |

**Comment by smalluban** [comment]
@GRadziejewski Branch updated with potential fix for syncing issues. No other changes, so if you have time, please check the case with the left device for an hour. This should be the last blocking issue from releasing this version.

**Comment by smalluban** [comment]
WARNING ❗❗❗

Do not merge main into the branch, as for now it also includes features not intended to be included in this release:
* https://github.com/ghostery/ghostery-extension/pull/1285

**Comment by smalluban** [comment]
TestFlight: 10.1.4 (124)

**Comment by GRadziejewski** [comment]
Tests are finished at 11:30:00 UTC 29.09.2023.

Test results of iteration nr 3 are here: [[QA] Tests of Release 10.1.4](https://github.com/ghostery/ghostery-extension/issues/1316#issuecomment-1739039067)

New issues:
- none

**Review by GRadziejewski — APPROVED** [review]

**Pull request merged**
