### PR TITLE
Release v10.4.16

### PR DESCRIPTION
**Pull request by smalluban**
d6603401ba990aa3f275eb52856af18563d213c1 feature(ad-blocking): `:has` filter support (#2082)
d44c5eac98ee82409b0940ef44f64f07aff1afc9 fix(ad-blocking): slow startup does not block ad-blocking (#2075)
029752f1a3a84cdb75580b7c304cb152b2474d3e fix(anti-tracking): compatibility list prevents request modifications (#2087)
cc00d69ae078851a517d10eb1d8fe4609c50b876 fix(account): improved synchronization timing (#2062)
0108b6dc2c388285bb5880948a4934fd175f0bdb fix(panel): shows UI even if extension didn't start (#2086)
5c2fdaf8db1bb0a62ce965766080a5e499951be6 fix(tests): improved e2e tests stability (#2080)

### CODE REVIEW

**Comment by smalluban** [comment]
@AdamGhst, I'll push the release to TestFlight, but we will not publish this version on Safari. Please test Safari as the last platform (normally, as we want to be sure that introduced changes work there too).

**Review by chrmod — APPROVED** [review]

**Review by Dimi-GE — COMMENTED** [review]
Got the error during tests on Chrome - not sure if the error is legit to reject the PR. Please, see the following screenshots:

388936500-2c20587c-bb03-48de-a4cd-f87d5eb9510e-1

388936559-2fc8396a-13d1-4af0-853a-72e27c083aaa

**Comment by smalluban** [comment]
@Dimi-GE Thanks for the comment. It checked the autoconsent.js file, and it must be a normal case - it's only a warning, and it is an internal part of the autoconsent library.

**Review by AdamGhst — APPROVED** [review]
Smoke Tests 10.4.16

macOS
Firefox - passed
Chrome - passed
Shatfari - passed

Win10
Edge - passed
Firefox - passed

**Pull request merged**
